### ISSUE TITLE
Kind help to run the code

### ISSUE THREAD

**Issue by enoche** [oklen/PEVAE#1] opened 2022-09-14 07:51 UTC
Hi, thanks for sharing the code.

May I have your help to run up the code.
1. Sharing of dataset (one is ok.)
2. Have you test your code before publishing? (Variables are not defined in model, functions are not defined everywhere?)

Thanks a lot.

**Comment by oklen** [comment] 2022-09-14 08:55
Hi, we rename a folder which may cause variable undefined and it should be fixed now. For data, we need reproducing data we used and then upload it. Please be patient as we are finishing another work.

**Comment by enoche** [comment] 2022-09-14 09:24
> 

Thanks for your reply. Waiting for your processed datasets.

**Comment by enoche** [comment] 2022-09-14 09:32
Also you help may be required to reproduce your results in Table 3. Thanks.

**Comment by algoflow19** [comment] 2022-09-27 14:37
Since @oklen is very busy, I will try to do this.

**Comment by algoflow19** [comment] 2022-10-12 11:43
We have uploaded the original dataset, you may process the it following instruction in our paper if you in a hurry.

**Comment by algoflow19** [comment] 2022-10-13 05:16
You may reopen it or raise a new issue if you have other problem.

**Closed as completed by algoflow19** 2022-10-13 05:16 UTC
